### ISSUE TITLE
Symbol names are not found for import unless the cursor is positioned at the end of the name

### ISSUE THREAD

**Issue by bytenik** [Sammons/ts-import-assistance#10]
For example:

![image](https://cloud.githubusercontent.com/assets/441347/16746695/84f4fb68-4789-11e6-952e-0de76ccb951b.png)

**Comment by Sammons** [comment]
@bytenik check it out in 0.0.6

In this version I also backtrack over a variety of special chars, and take the first word as the victor for the symbol to guess. This means having the cursor inside or after `abc.b.c().d` should result in `abc` being imported.

Please confirm this is what you are looking for when you get a chance.

Thanks!

**Comment by bytenik** [comment]
Nope, not quite:

![image](https://cloud.githubusercontent.com/assets/441347/16807379/27b51c0e-48e6-11e6-81b3-9d3a753e1f52.png)

This actually seems to have broken previous working behavior when positioned at the end of the symbol. I think you're backtracking correctly but not detecting the end of the symbol properly.

**Comment by bytenik** [comment]
If I highlight the symbol and resolve, it does work. However, I _also_ get that same error from above (including the comma, which is not highlighted).

**Comment by Sammons** [comment]
I see, my bad, I'm surprised this wasn't causing errors elsewhere. Should be fixed now in 0.0.7

**Comment by bytenik** [comment]
Closer but still not quite. In the following screenshot, running resolve on the `OrdinalPipe` symbol (with cursor as positioned) yields no error but also yields no import. If I highlight just the symbol without the brackets, it works.

![image](https://cloud.githubusercontent.com/assets/441347/16844446/30f5a374-49b3-11e6-8800-cefeca85727d.png)

**Comment by Sammons** [comment]
This thread will go forever at this rate, I'll fix this when I can, I think in general that behavior comes from trying to import an empty string.

**Comment by Sammons** [comment]
@bytenik on to the next one ;)

**Comment by bytenik** [comment]
Works!
